name: Environment with Inputs

on:
 workflow_dispatch:
  inputs:
   TARGET ENVIRONMENT:
    type: environment
    default: devexvar
jobs:
   build:
      runs-on: ubuntu-latest
      environment: ${{inputs.TARGET_ENVIRONMENT}}
      steps:
       - name: Display secret
         run: echo 'variable value is ${{var.TAR_VAR}}'
       
