name: First Workflowtest CI

on: 
  push:
   branches:
    - feature1
    - ! main

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - run: echo 'build'

 test:
    runs-on: windows-latest
    steps:
      - run: echo 'test'
