name: First Workflowtest CI

on: 
  push:
   branches:
    - 'feature1'
    - 'main'

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Setup Java JDK
       uses: actions/setup-java@v4.6.0
       with: 
         java-version: '17'
         distribution: 'microsoft'

 test:
    runs-on: windows-latest
    steps:
      - run: echo 'test'
