name: Build and push
run-name: ${{input.debug}}

on:
 workflow_dispatch: 
  inputs:
   debug:
    type: boolean
    default: false
env:
  DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PSWD}} 

jobs:
   build:
    env:
     DOCKER_IMAGE: job
    runs-on: ubuntu-latest
    steps:
     - name: Display  
       run: |
        echo '${{env.DOCKER_USERNAME}}';
        echo '${{env.DOCKER_PASSWORD}}'
        
   
