name: Build and push
env:
 DOCKER_IMAGE: workflow
on:
 push: 
  branches:
   - main

jobs:
   build:
    env:
     DOCKER_IMAGE: job
    runs-on: ubuntu-latest
    steps:
     - name: Display
       env:
        DOCKER_IMAGE: steps
       run: echo '${{env.DOCKER_IMAGE}}'
        
   
