name: Build and push
env:
 DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
on:
 push: 
  branches:
   - main

jobs:
   build:
    env:
     DOCKER_IMAGE: job
    runs-on: ubuntu-latest
    steps:
     - name: Display
       env:
        DOCKER_IMAGE: steps
       run: echo '${{env.DOCKER_USERNAME}}'
        
   
