name: Node JS

on:
 workflow_dispatch:
  
jobs:
 build-node:
  runs-on:  ${{matrix.os}}
  strategy:
   matrix:
    node_version: [v21,v22,v23]
    os:
     - ubuntu-latest
     - windows-latest
  steps:
   - name: Setup Node.js environment
     uses: actions/setup-node@v3.9.1
     with:
       node-version: ${{matrix.node-version}}
