name: Strategy

on: 
 workflow_dispatch:

 #continue-on-error : allows the workflow to continue even if anything fails
 #fail-fast: stops all which are in progress as well as future jobs one stop at a time. - critical CI/CD - any failures -halt all
jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   fail-fast: true
   matrix:
    node-version: [22,25,24]
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.9.1
      with:
       node-version: ${{matrix.node-version}}
